version: '2'
services:
    lab:
        build: .
        image: webdriverio:latest
        environment:
            - SELENIUM_HUB_HOST=hub
            - SELENIUM_HUB_PORT=4444
        depends_on:
            - chrome
            - firefox
        volumes:
            - .:/opt/webdriverio
    hub:
        image: selenium/hub
        ports:
            - 4444:4444
    firefox:
        image: selenium/node-firefox
        ports:
            - 5900
        environment:
            - HUB_PORT_4444_TCP_ADDR=hub
        depends_on:
            - hub
    chrome:
        image: selenium/node-chrome
        ports:
            - 5900
        environment:
            - HUB_PORT_4444_TCP_ADDR=hub
        depends_on:
            - hub
        volumes:
            - ./config.json:/opt/selenium/config.json